### PR TITLE
Support aws-vpc-cni

### PR DESCRIPTION
**Pull request by joshrosso**
In order to support routable pod IPs, required by gimbal and isito's
multicluster functionality, this commit introduces the used of
aws-vpc-cni plugin, which provides pods IPv4 addresses available in the
VPC. It still runs Calico, but instead runs in 'Policy Only' mode where
it is only responsible for enforcing NetworkPolicy and not concerned
with routing / BGP.

### CODE REVIEW

**Comment by joshrosso** [comment]
@lander2k2 @tvalasek

This commit should contain everything needed to enable `aws-vpc-cni`+`calico-node` (policy-only mode) in clusters.

This results in routable pod IPs via AWS ENIs, nodes now look as follows:

image

(sorry for weird lines)

**Comment by lander2k2** [comment]
@joshrosso 

Wondering why you used:`ExecStartPre=/usr/bin/bash -c "/usr/bin/systemctl set-environment KUBELET_NODE_IP=--node-ip=$(curl http://169.254.169.254/latest/meta-data/local-ipv4)"`

**Comment by joshrosso** [comment]
@lander2k2, I was actually going off the https://github.com/aws/amazon-vpc-cni-k8s#setup recommendation for setting `--node-ip`. I think the thought process would be this approach would make the kubelet config dyanamic...in that if the ip were to change on a node, the kubelet would restart with the correct IP. 

Since this shouldn't happen, we could be OK with `PRIVATE_IP`.

**Comment by lander2k2** [comment]
Changing base branch and merging.

**Pull request merged**
